Fashion/Fashion/Models/Mal.cs
namespace Fashion.Models;

public class Mal
{
    public int Id { get; set; }
    public string Name { get; set; }
    
    
    public string ImageUrl { get; set; }
    public decimal Price { get; set; }

}

Fashion/Fashion/Areas/Admin/Controllers/DashboardController.cs
using Fashion.Models;
using Fashion.Services;
using Microsoft.AspNetCore.Mvc;

namespace Fashion.Areas.Admin.Controllers;
[Area("Admin")]

public class DashboardController : Controller
{
    private readonly MalServic _malServic;
    public DashboardController()
    {
        _malServic = new MalServic();
    }
    public IActionResult Index()
    {
        

        return View();
    }
}

Fashion/Fashion/Areas/Admin/Controllers/MalController.cs
using Fashion.Models;
using Fashion.Services;
using Microsoft.AspNetCore.Mvc;

namespace Fashion.Areas.Admin.Controllers;
[Area("Admin")]

public class MalController : Controller
{
    private readonly MalServic _malServic;
    public MalController()
    {
        _malServic = new MalServic();
    }
    [HttpGet]
    public IActionResult Index()
    { List<Mal> mals = _malServic.GetAllMals();
        return View(mals);
    }
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    public IActionResult Create(Mal mal)
    {
        _malServic.CreateMal(mal);
        return RedirectToAction(nameof(Index));
    }
    [HttpGet]
    public IActionResult Update(int id)
    {
        Mal mal = _malServic.GetMalById(id);
        return View(mal);
    }
    [HttpPost]
    public IActionResult Update(int Id ,Mal mal)
    {
        _malServic.updateMal(Id,mal);

        return RedirectToAction(nameof(Index));
    }

}

Fashion/Fashion/Controllers/HomeController.cs
using Fashion.Models;
using Fashion.Services;
using Microsoft.AspNetCore.Mvc;

namespace Fashion.Controllers
{
    public class HomeController : Controller
    {
        private readonly MalServic _malServic;
        public HomeController()
        {
            _malServic = new MalServic();
        }
        public IActionResult Index()
        {
            List<Mal> mals = _malServic.GetAllMals();
            return View(mals);
        }
    }
}

Fashion/Fashion/Areas/Admin/Views/Mal/Create.cshtml
@using Fashion.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@model Mal
<div class="container-fluid pt-5 px-4 mt-5">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-6 offset-xl-6">
            <!-- Mərkəzdən sağa sürüşdü -->
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4 text-end">Basic Form</h6>

                <form asp-area="admin" asp-controller="Mal" asp-action="Create" method="Post" class="text-end" style="margin-top: 100px; direction: rtl;">
                    

                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">ImageUrl</label>
                        <input asp-for="ImageUrl" class="form-control text-end" id="exampleInputPassword1">
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Name</label>
                        <input asp-for="Name" class="form-control text-end" id="exampleInputPassword1">
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Price</label>
                        <input asp-for="Price" class="form-control text-end" id="exampleInputPassword1">
                    </div>


                    <button type="submit" class="btn btn-primary">Create</button>
                </form>

            </div>
        </div>
    </div>
</div>

Fashion/Fashion/Areas/Admin/Views/Mal/Update.cshtml
@using Fashion.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@model Mal
<div class="container-fluid pt-5 px-4 mt-5">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-6 offset-xl-6">
            <!-- Mərkəzdən sağa sürüşdü -->
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4 text-end">update mal form</h6>

                <form asp-area="admin" asp-controller="Mal" asp-action="Update" method="Post" class="text-end" style="margin-top: 100px; direction: rtl;">


                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">ImageUrl</label>
                        <input asp-for="ImageUrl" class="form-control text-end" id="exampleInputPassword1">
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Name</label>
                        <input asp-for="Name" class="form-control text-end" id="exampleInputPassword1">
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Price</label>
                        <input asp-for="Price" class="form-control text-end" id="exampleInputPassword1">
                    </div>


                    <button type="submit" class="btn btn-primary">Update</button>
                </form>

            </div>
        </div>
    </div>
</div>

Fashion/Fashion/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>DarkPan - Bootstrap 5 Admin Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/admin/assets/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/admin/assets/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/admin/assets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/admin/assets/css/style.css" rel="stylesheet">
</head>

<body>
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-secondary navbar-dark">
                <a href="index.html" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary"><i class="fa fa-user-edit me-2"></i>DarkPan</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="~/admin/assets/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">Jhon Doe</h6>
                        <span>Admin</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="index.html" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-laptop me-2"></i>Elements</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="button.html" class="dropdown-item">Buttons</a>
                            <a href="typography.html" class="dropdown-item">Typography</a>
                            <a href="element.html" class="dropdown-item">Other Elements</a>
                        </div>
                    </div>
                    <a href="widget.html" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Widgets</a>
                    <a href="form.html" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Forms</a>
                    <a href="table.html" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Tables</a>
                    <a href="chart.html" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>Charts</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="far fa-file-alt me-2"></i>Pages</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="signin.html" class="dropdown-item">Sign In</a>
                            <a href="signup.html" class="dropdown-item">Sign Up</a>
                            <a href="404.html" class="dropdown-item">404 Error</a>
                            <a href="blank.html" class="dropdown-item">Blank Page</a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->
        @RenderBody()

        <div class="container-fluid pt-4 px-4">
            <div class="bg-secondary rounded-top p-4">
                <div class="row">
                    <div class="col-12 col-sm-6 text-center text-sm-start">
                        &copy; <a href="#">Your Site Name</a>, All Right Reserved.
                    </div>
                    <div class="col-12 col-sm-6 text-center text-sm-end">
                        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                        Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                        <br>Distributed By: <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
    </div>
    <!-- Content End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/admin/assets/lib/chart/chart.min.js"></script>
    <script src="~/admin/assets/lib/easing/easing.min.js"></script>
    <script src="~/admin/assets/lib/waypoints/waypoints.min.js"></script>
    <script src="~/admin/assets/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/admin/assets/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/admin/assets/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/admin/assets/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/admin/assets/js/main.js"></script>
</body>

</html>

        

Fashion/Fashion/Views/Home/Index.cshtml
@using Fashion.Models
@model List<Mal>

<section class="slick-slideshow">
    <div class="slick-custom">
        <img src="~/assets/images/slideshow/medium-shot-business-women-high-five.jpeg" class="img-fluid" alt="">

        <div class="slick-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-10">
                        <h1 class="slick-title">Cool Fashion</h1>

                        <p class="lead text-white mt-lg-3 mb-lg-5">Little fashion template comes with total 8 HTML pages provided by Tooplate website.</p>

                        <a href="about.html" class="btn custom-btn">Learn more about us</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="slick-custom">
        <img src="~/assets/images/slideshow/team-meeting-renewable-energy-project.jpeg" class="img-fluid" alt="">

        <div class="slick-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-10">
                        <h1 class="slick-title">New Design</h1>

                        <p class="lead text-white mt-lg-3 mb-lg-5">Please share this Little Fashion template to your friends. Thank you for supporting us.</p>

                        <a href="product.html" class="btn custom-btn">Explore products</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="slick-custom">
        <img src="~/assets/images/slideshow/two-business-partners-working-together-office-computer.jpeg" class="img-fluid" alt="">

        <div class="slick-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-10">
                        <h1 class="slick-title">Talk to us</h1>

                        <p class="lead text-white mt-lg-3 mb-lg-5">Tooplate is one of the best HTML CSS template websites for everyone.</p>

                        <a href="contact.html" class="btn custom-btn">Work with us</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

<section class="about section-padding">
    <div class="container">
        <div class="row">

            <div class="col-12 text-center">
                <h2 class="mb-5">Get started with <span>Little</span> Fashion</h2>
            </div>

            <div class="col-lg-2 col-12 mt-auto mb-auto">
                <ul class="nav nav-pills mb-5 mx-auto justify-content-center align-items-center" id="pills-tab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Introduction</button>
                    </li>

                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="pills-youtube-tab" data-bs-toggle="pill" data-bs-target="#pills-youtube" type="button" role="tab" aria-controls="pills-youtube" aria-selected="true">How we work?</button>
                    </li>

                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="pills-skill-tab" data-bs-toggle="pill" data-bs-target="#pills-skill" type="button" role="tab" aria-controls="pills-skill" aria-selected="false">Capabilites</button>
                    </li>
                </ul>
            </div>

            <div class="col-lg-10 col-12">
                <div class="tab-content mt-2" id="pills-tabContent">
                    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">

                        <div class="row">
                            <div class="col-lg-7 col-12">
                                <img src="~/assets/images/pim-chu-z6NZ76_UTDI-unsplash.jpeg" class="img-fluid" alt="">
                            </div>

                            <div class="col-lg-5 col-12">
                                <div class="d-flex flex-column h-100 ms-lg-4 mt-lg-0 mt-5">
                                    <h4 class="mb-3">Good <span>Design</span> <br>Ideas for <span>your</span> fashion</h4>

                                    <p>Little Fashion templates comes with <a href="sign-in.html">sign in</a> / <a href="sign-up.html">sign up</a> pages, product listing / product detail, about, FAQs, and contact page.</p>

                                    <p>Since this HTML template is based on Boostrap 5 CSS library, you can feel free to add more components as you need.</p>

                                    <div class="mt-2 mt-lg-auto">
                                        <a href="about.html" class="custom-link mb-2">
                                            Learn more about us
                                            <i class="bi-arrow-right ms-2"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="tab-pane fade" id="pills-youtube" role="tabpanel" aria-labelledby="pills-youtube-tab">

                        <div class="row">
                            <div class="col-lg-7 col-12">
                                <div class="ratio ratio-16x9">
                                    <iframe src="https://www.youtube-nocookie.com/embed/f_7JqPDWhfw?controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                </div>
                            </div>

                            <div class="col-lg-5 col-12">
                                <div class="d-flex flex-column h-100 ms-lg-4 mt-lg-0 mt-5">
                                    <h4 class="mb-3">Life at Studio</h4>

                                    <p>Over three years in business, We’ve had the chance to work on a variety of projects, with companies</p>

                                    <p>Custom work is branding, web design, UI/UX design</p>

                                    <div class="mt-2 mt-lg-auto">
                                        <a href="contact.html" class="custom-link mb-2">
                                            Work with us
                                            <i class="bi-arrow-right ms-2"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="tab-pane fade" id="pills-skill" role="tabpanel" aria-labelledby="pills-skill-tab">
                        <div class="row">
                            <div class="col-lg-7 col-12">
                                <img src="~/assets/images/cody-lannom-G95AReIh_Ko-unsplash.jpeg" class="img-fluid" alt="">
                            </div>

                            <div class="col-lg-5 col-12">
                                <div class="d-flex flex-column h-100 ms-lg-4 mt-lg-0 mt-5">
                                    <h4 class="mb-3">What can help you?</h4>

                                    <p>Over three years in business, We’ve had the chance on projects</p>

                                    <div class="skill-thumb mt-3">

                                        <strong>Branding</strong>
                                        <span class="float-end">90%</span>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%;"></div>
                                        </div>

                                        <strong>Design & Stragety</strong>
                                        <span class="float-end">70%</span>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%;"></div>
                                        </div>

                                        <strong>Online Platform</strong>
                                        <span class="float-end">80%</span>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%;"></div>
                                        </div>

                                    </div>

                                    <div class="mt-2 mt-lg-auto">
                                        <a href="products.html" class="custom-link mb-2">
                                            Explore products
                                            <i class="bi-arrow-right ms-2"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
</section>

<section class="front-product">
    <div class="container-fluid p-0">
        <div class="row align-items-center">

            <div class="col-lg-6 col-12">
                <img src="~/assets/images/retail-shop-owner-mask-social-distancing-shopping.jpg" class="img-fluid" alt="">
            </div>

            <div class="col-lg-6 col-12">
                <div class="px-5 py-5 py-lg-0">

                    <h2 class="mb-4"><span>Retail</span> shop owners</h2>

                    <p class="lead mb-4">Credits go to Unsplash and FreePik websites for images used in this Little Fashion by Tooplate.</p>

                    <a href="products.html" class="custom-link">
                        Explore Products
                        <i class="bi-arrow-right ms-2"></i>
                    </a>
                </div>
            </div>

        </div>
    </div>
</section>

<section class="featured-product section-padding">
    <div class="container">
        <div class="row">

            <div class="col-12 text-center">
                <h2 class="mb-5">Featured Products</h2>
            </div>



            @foreach(Mal item in Model)
            {
                <div class="col-lg-4 col-12 mb-3">
                    <div class="product-thumb">
                        <a href="product-detail.html">
                            <img src="~/assets/images/product/@item.ImageUrl" class="img-fluid product-image" alt="">
                        </a>

                        <div class="product-top d-flex">
                            <span class="product-alert">Low Price</span>

                            <a href="#" class="bi-heart-fill product-icon ms-auto"></a>
                        </div>

                        <div class="product-info d-flex">
                            <div>
                                <h5 class="product-title mb-0">
                                    <a href="product-detail.html" class="product-title-link">@item.Name</a>
                                </h5>

                                <p class="product-p"></p>
                            </div>

                            <small class="product-price text-muted ms-auto mt-auto mb-5">@item.Price</small>
                        </div>
                    </div>
                </div>
            }

                    

                    <div class="col-12 text-center">
                        <a href="products.html" class="view-all">View All Products</a>
                    </div>

                </div>
            </div>
        </section>

    </main>

   

Fashion/Fashion/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <title>Tooplate's Little Fashion</title>

    <!-- CSS FILES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;300;400;700;900&display=swap" rel="stylesheet">

    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/css/bootstrap-icons.css" rel="stylesheet">

    <link rel="stylesheet" href="~/assets/css/slick.css" />

    <link href="~/assets/css/tooplate-little-fashion.css" rel="stylesheet">
    <!--

    Tooplate 2127 Little Fashion

    https://www.tooplate.com/view/2127-little-fashion

    -->
</head>

<body>

    <section class="preloader">
        <div class="spinner">
            <span class="sk-inner-circle"></span>
        </div>
    </section>

    <main>

        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <a class="navbar-brand" href="index.html">
                    <strong><span>Little</span> Fashion</strong>
                </a>

                <div class="d-lg-none">
                    <a href="sign-in.html" class="bi-person custom-icon me-3"></a>

                    <a href="product-detail.html" class="bi-bag custom-icon"></a>
                </div>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="index.html">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="about.html">Story</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="products.html">Products</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="faq.html">FAQs</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="contact.html">Contact</a>
                        </li>
                    </ul>

                    <div class="d-none d-lg-block">
                        <a href="sign-in.html" class="bi-person custom-icon me-3"></a>

                        <a href="product-detail.html" class="bi-bag custom-icon"></a>
                    </div>
                </div>
            </div>
        </nav>
        @RenderBody()
        <footer class="site-footer">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-10 me-auto mb-4">
                        <h4 class="text-white mb-3"><a href="index.html">Little</a> Fashion</h4>
                        <p class="copyright-text text-muted mt-lg-5 mb-4 mb-lg-0">Copyright © 2022 <strong>Little Fashion</strong></p>
                        <br>
                        <p class="copyright-text">Designed by <a href="https://www.tooplate.com/" target="_blank">Tooplate</a></p>
                    </div>

                    <div class="col-lg-5 col-8">
                        <h5 class="text-white mb-3">Sitemap</h5>

                        <ul class="footer-menu d-flex flex-wrap">
                            <li class="footer-menu-item"><a href="about.html" class="footer-menu-link">Story</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">Products</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">Privacy policy</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">FAQs</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">Contact</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-4">
                        <h5 class="text-white mb-3">Social</h5>

                        <ul class="social-icon">

                            <li><a href="#" class="social-icon-link bi-youtube"></a></li>

                            <li><a href="#" class="social-icon-link bi-whatsapp"></a></li>

                            <li><a href="#" class="social-icon-link bi-instagram"></a></li>

                            <li><a href="#" class="social-icon-link bi-skype"></a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </footer>

        <!-- JAVASCRIPT FILES -->
        <script src="~/assets/js/jquery.min.js"></script>
        <script src="~/assets/js/bootstrap.bundle.min.js"></script>
        <script src="~/assets/js/Headroom.js"></script>
        <script src="~/assets/js/jQuery.headroom.js"></script>
        <script src="~/assets/js/slick.min.js"></script>
        <script src="~/assets/js/custom.js"></script>

</body>
</html>